### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by tedstriker** [jachwe/node-caldav#4]
Hello,
Out of curiosity: is your project still maintained, but hasn’t seen updated because it just works or has it been abondened?

**Comment by jachwe** [comment]
Hi. I didn't use the project myself in a while but had no major issues. So i "assume" it just works. ;-)
If needed and time allows, i am still willing to jumo into the code again.

**Comment by tedstriker** [comment]
Good to hear, thank you for your quick response
